import React from 'react'

import Layout from '../components/layout'

const Privacy = () => (
  <Layout>
    <div id="wrap">
      <div className="page-header">
        <div className="container">
          <div className="row">
            <div className="col-md-12">
              <h1>AY Sing</h1>
            </div>
          </div>
        </div>
      </div>

      <div className="page-agreement">
        <div className="container">
          <div className="row">
            <div className="col-md-12">
              <div className="tab-content">
                <h1>Privacy Policy</h1>

                <p>Effective date: June 05, 2019</p>

                <p>
                  AY Sing ("us", "we", or "our") operates the AY Sing mobile
                  application (hereinafter referred to as the "Service").
                </p>

                <p>
                  This page informs you of our policies regarding the
                  collection, use, and disclosure of personal data when you use
                  our Service and the choices you have associated with that
                  data. The Privacy Policy for AY Sing has been created with the
                  help of <a href="https://www.termsfeed.com/">TermsFeed</a>.
                </p>

                <h2>Definitions</h2>
                <ul>
                  <li>
                    <p>
                      <strong>Service</strong>
                    </p>
                    <p>
                      Service is the AY Sing mobile application operated by AY
                      Sing
                    </p>
                  </li>
                  <li>
                    <p>
                      <strong>Personal Data</strong>
                    </p>
                    <p>
                      Personal Data means data about a living individual who can
                      be identified from those data (or from those and other
                      information either in our possession or likely to come
                      into our possession).
                    </p>
                  </li>
                  <li>
                    <p>
                      <strong>Usage Data</strong>
                    </p>
                    <p>
                      Usage Data is data collected automatically either
                      generated by the use of the Service or from the Service
                      infrastructure itself (for example, the duration of a page
                      visit).
                    </p>
                  </li>
                  <li>
                    <p>
                      <strong>Cookies</strong>
                    </p>
                    <p>
                      Cookies are small files stored on your device (computer or
                      mobile device).
                    </p>
                  </li>
                </ul>

                <h2>Information Collection and Use</h2>
                <p>
                  We collect several different types of information for various
                  purposes to provide and improve our Service to you.
                </p>

                <h3>Types of Data Collected</h3>

                <h4>Personal Data</h4>
                <p>
                  While using our Service, we may ask you to provide us with
                  certain personally identifiable information that can be used
                  to contact or identify you ("Personal Data"). Personally
                  identifiable information may include, but is not limited to:
                </p>

                <ul>
                  <li>Email Address</li>
                </ul>

                <h2>Use of Data</h2>

                <p>AY Sing uses the collected data for various purposes:</p>
                <ul>
                  <li>To respond to you feedback requests when sent by you.</li>
                </ul>

                <h2>Transfer Of Data</h2>
                <p>
                  Your information, including Personal Data, may be transferred
                  to - and maintained on - computers located outside of your
                  state, province, country or other governmental jurisdiction
                  where the data protection laws may differ than those from your
                  jurisdiction.
                </p>
                <p>
                  If you are located outside Barbados and choose to provide
                  information to us, please note that we transfer the data,
                  including Personal Data, to Barbados and process it there.
                </p>
                <p>
                  Your consent to this Privacy Policy followed by your
                  submission of such information represents your agreement to
                  that transfer.
                </p>
                <p>
                  AY Sing will take all steps reasonably necessary to ensure
                  that your data is treated securely and in accordance with this
                  Privacy Policy and no transfer of your Personal Data will take
                  place to an organization or a country unless there are
                  adequate controls in place including the security of your data
                  and other personal information.
                </p>

                <h2>Disclosure Of Data</h2>

                <h3>Legal Requirements</h3>
                <p>
                  AY Sing may disclose your Personal Data in the good faith
                  belief that such action is necessary to:
                </p>
                <ul>
                  <li>To comply with a legal obligation</li>
                  <li>
                    To protect and defend the rights or property of AY Sing
                  </li>
                  <li>
                    To prevent or investigate possible wrongdoing in connection
                    with the Service
                  </li>
                  <li>
                    To protect the personal safety of users of the Service or
                    the public
                  </li>
                  <li>To protect against legal liability</li>
                </ul>

                <p>
                  As an European citizen, under GDPR, you have certain
                  individual rights. You can learn more about these guides in
                  the &nbsp;
                  <a href="https://termsfeed.com/blog/gdpr/#Individual_Rights_Under_the_GDPR">
                    GDPR Guide
                  </a>
                  .
                </p>

                <h2>Security of Data</h2>
                <p>
                  The security of your data is important to us but remember that
                  no method of transmission over the Internet or method of
                  electronic storage is 100% secure. While we strive to use
                  commercially acceptable means to protect your Personal Data,
                  we cannot guarantee its absolute security.
                </p>

                <h2>Service Providers</h2>
                <p>
                  We may employ third party companies and individuals to
                  facilitate our Service ("Service Providers"), to provide the
                  Service on our behalf, to perform Service-related services or
                  to assist us in analyzing how our Service is used.
                </p>
                <p>
                  These third parties have access to your Personal Data only to
                  perform these tasks on our behalf and are obligated not to
                  disclose or use it for any other purpose.
                </p>

                <h2>Changes to This Privacy Policy</h2>
                <p>
                  We may update our Privacy Policy from time to time. We will
                  notify you of any changes by posting the new Privacy Policy on
                  this page.
                </p>
                <p>
                  We will let you know via email and/or a prominent notice on
                  our Service, prior to the change becoming effective and update
                  the "effective date" at the top of this Privacy Policy.
                </p>
                <p>
                  You are advised to review this Privacy Policy periodically for
                  any changes. Changes to this Privacy Policy are effective when
                  they are posted on this page.
                </p>

                <h2>Contact Us</h2>
                <p>
                  If you have any questions about this Privacy Policy, please
                  contact us:
                </p>
                <ul>
                  <li>By email: kroach.apps@gmail.com</li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="page-footer">
        <div className="container">
          <div className="row">
            <div className="col-md-12">Privacy Policy of AY Sing</div>
          </div>
        </div>
      </div>
    </div>

    <style global jsx>
      {`
        body {
          background: #f4f9fd;
          font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
          font-size: 14px;
          line-height: 1.42857143;
          color: #333;
          background-color: #fff;
        }

        .container {
          margin-right: auto;
          margin-left: auto;
          padding-left: 15px;
          padding-right: 15px;
        }
        @media (min-width: 768px) {
          .container {
            width: 750px;
          }
        }
        @media (min-width: 992px) {
          .container {
            width: 970px;
          }
        }
        @media (min-width: 1200px) {
          .container {
            width: 1170px;
          }
        }
        .page-header {
          margin: 0;
          padding: 40px 0;
          border-bottom: 1px solid #eee;
          background: #fff;
        }
        .page-header h1 {
          font-size: 25px;
          line-height: 35px;
          margin: 0;
        }
        .page-agreement {
          padding: 30px 0;
          background: #f4f9fd;
        }
        .page-agreement .page-tabs .nav-tabs {
          border: 0;
          margin: 10px 0 30px 0;
        }
        .page-agreement .page-tabs .nav-tabs li a {
          border: 1px solid #eee;
          border-radius: 5px;
          background: #fff;
        }
        .page-agreement .page-tabs .nav-tabs li.active a {
          background: #0053a7;
          color: #fff;
        }
        .page-agreement .tab-content {
          font-size: 18px;
          line-height: 28px;
          word-wrap: break-word;
        }
        .page-agreement .tab-content h1 {
          font-size: 30px;
          margin: 0 0 30px 0;
        }
        .page-agreement .tab-content h2 {
          font-size: 24px;
          margin: 0 0 30px 0;
        }
        .page-agreement .tab-content h3 {
          font-size: 20px;
          margin: 0 0 30px 0;
        }
        .page-agreement .tab-content h4 {
          font-size: 16px;
          margin: 0 0 30px 0;
        }
        .page-agreement .tab-content p {
          margin: 0 0 30px 0;
          color: #333;
        }
        .page-agreement .tab-content ul,
        .page-agreement .tab-content ol {
          margin: 0 0 30px 0;
        }
        .page-agreement .tab-content a {
          color: #333;
        }
        .page-footer {
          background: #454954;
          padding: 30px 0;
          color: #fff;
          font-size: 16px;
          line-height: 20px;
        }
        .page-credits {
          background: #17191d;
          padding: 20px 0;
          color: #fff;
          font-size: 14px;
          line-height: 18px;
        }
        .page-credits p {
          margin: 0;
        }
        .page-credits a {
          color: #eee;
        }
      `}
    </style>
  </Layout>
)

export default Privacy
